### ISSUE TITLE
Can't interact with contract

### ISSUE THREAD

**Issue by thedarkjester** [juanbenitez/blockchain-developer-bootcamp-final-project#1]
Hi,

I am trying to mark your project but am encountering an error when adding a certificate. The same happens when testing locally.

Please could you correct this so that I am able to continue:

![image](https://user-images.githubusercontent.com/3957173/144926850-12f0be9b-2872-4f72-ae8e-1a3423818f3f.png)

**Comment by juanbenitez** [comment]
Hi @thedarkjester , in order to create a certificate both arguments should be filled (seems that's the problem here):
- the certificate title, just a string for naming the certificate
- the certificate valid period, an integer that state the number of days the certificate is valid.

Sorry for the UI/UX, I know it's very basic...

![create-cert](https://user-images.githubusercontent.com/2771799/145017438-0f593938-a548-4a55-84c4-fd15e0f58422.png)

That being said, you can test this feature locally but you won't be able to do it in the online version because in order to create a certificate the account must have the **_'tutor'_** role. So for the online version I can grant you (manually) the **'tutor'** role if you share the account address you need.

Locally, the deployer's account is assigned with the **'tutor'** role on the initialization. Also, you can set more **'tutor'** accounts manually by using the script located in the scripts folder, please read [this section](https://github.com/juanbenitez/blockchain-developer-bootcamp-final-project#setting-tutor-role) in the README for more info.

Hope this could help you and let me know if you need anything else.
Thanks for your time.

**Comment by thedarkjester** [comment]
aaah, gotcha - my bad - the UI was indeed my issue. all working now - nice job
